// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxN1JTs8qEjAoTXGYIyN-w4RRlyGTbnQk',
    appId: '1:793994215134:web:651be5da895fd518fecc4f',
    messagingSenderId: '793994215134',
    projectId: 'tlu-tutor',
    authDomain: 'tlu-tutor.firebaseapp.com',
    storageBucket: 'tlu-tutor.appspot.com',
    measurementId: 'G-SC0Y6DVE7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjdrxnuC8plTbybCzKf1ZRXVqB0BLl7wU',
    appId: '1:793994215134:android:1c5ad10ee02a20d2fecc4f',
    messagingSenderId: '793994215134',
    projectId: 'tlu-tutor',
    storageBucket: 'tlu-tutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmWSnKTfrem3h83PlCUB3_IdIKudQ2RPU',
    appId: '1:793994215134:ios:bdc1b763dd57595ffecc4f',
    messagingSenderId: '793994215134',
    projectId: 'tlu-tutor',
    storageBucket: 'tlu-tutor.appspot.com',
    iosBundleId: 'com.example.datn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmWSnKTfrem3h83PlCUB3_IdIKudQ2RPU',
    appId: '1:793994215134:ios:7f6b99e35b572b3dfecc4f',
    messagingSenderId: '793994215134',
    projectId: 'tlu-tutor',
    storageBucket: 'tlu-tutor.appspot.com',
    iosBundleId: 'com.example.datn.RunnerTests',
  );
}
